#pragma once

constexpr int NUM_DISTRIBUTION_GRAPHS = 41;
constexpr int NUM_BIAS_GRAPHS = 21;
constexpr int NUM_DISTRIBUTION_BINS = 61;

extern const float DISTRIBUTION_GRAPHS[NUM_DISTRIBUTION_GRAPHS][NUM_BIAS_GRAPHS][NUM_DISTRIBUTION_BINS];
